services:

  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'
    container_name: redis

  web1:
    build: ./web
    image: 954692414134.dkr.ecr.ap-south-1.amazonaws.com/capstone-repo:web1-${TAG_VALUE}
    container_name: web1
    restart: on-failure
    hostname: web1
    ports:
      - '81:5000'
    volumes:
      - ./tests:/test   # <-- Mount tests folder

  web2:
    build: ./web
    image: 954692414134.dkr.ecr.ap-south-1.amazonaws.com/capstone-repo:web2-${TAG_VALUE}
    container_name: web2
    restart: on-failure
    hostname: web2
    ports:
      - '82:5000'
    volumes:
      - ./tests:/test   # <-- Mount tests folder

  nginx:
    build: ./nginx
    image: 954692414134.dkr.ecr.ap-south-1.amazonaws.com/capstone-repo:nginx-${TAG_VALUE}
    container_name: nginx
    ports:
      - '80:80'
    depends_on:
      - web1
      - web2
    volumes:
      - ./tests:/test   # <-- Mount tests folder
